# Generated by Django 3.2.15 on 2022-09-23 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20220921_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-id',)},
        ),
    ]
