# Generated by Django 3.2.15 on 2022-09-21 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentshub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contentshub_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='klass',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contentshub_klass', to='contentshub.master'),
        ),
    ]
